# Generated by Django 5.2.11 on 2026-02-21 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSyncState',
            fields=[
                ('sku', models.CharField(help_text='ID produktu (SKU)', max_length=100, primary_key=True, serialize=False)),
                ('data_hash', models.CharField(help_text='SHA-256 hash transformovaných dat', max_length=64)),
                ('last_synced_at', models.DateTimeField(auto_now=True, help_text='Čas poslední úspěšné synchronizace')),
            ],
        ),
    ]
